name: .NET GOLF CLUB

on:
  push:
    branches: [ main ]  # Run workflow on pushes to the main branch
  pull_request:
    branches: [ main ]  # Run workflow on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'  

    - name: Build project
      run: dotnet build
